name: 'Jekyll Deploy Action'

description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages

branding:
  icon: 'command'
  color: 'red'

inputs:
  id:
    description: The id according to os
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  actor:
    description: 'The github username creating the commit'
    default: '${GITHUB_ACTOR}'
    required: false
  token:
    description: 'The deploy token'
    required: false
  provider:
    description: 'The deploy provider'
    required: true
  repository:
    description: 'The deploy repository'
    required: false
  credentials:
    description: 'The gcloud credentials'
    required: true
  pauli_sum:
    description: 'The pre-build configuration'
    required: true
  failure_status:
    description: 'The deploy branch'
    required: false

outputs:
  all_outputs:
    description: Collect all outputs
    value: ${{ toJSON(steps.*.outputs) }}

runs:
  #using: 'node20'
  #main: '.github/run/main.js'
  #post: '.github/run/post.js'
  #post-if: 'success()'
  using: composite
  
  steps:
    - name: 🏗️ Collect output
      if: runner.os != 'macOS'
      uses: mathiasvr/command-output@v2.0.0
      id: command
      with:
        run: |
          date +'%Y-%m-%d'

    - name: 💎 Get the latest commit message
      id: commit
      shell: bash
      run: |
        git config --global user.name "${{ inputs.actor }}"
        git config --global user.email "${{ inputs.actor }}@users.noreply.github.com"

        git config --global core.autocrlf false
        git config --global --add safe.directory "${{ github.workspace }}"       
       
        git config --global credential.helper store
        echo "https://${{ inputs.actor }}:${{ inputs.token }}@github.com" > ~/.git-credentials

        echo 'REMOTE_REPO="https://${{ inputs.actor }}:${{ inputs.token }}@github.com/${{ github.repository }}.git"' >> ${GITHUB_ENV}
        echo 'LATEST_COMMIT='$(curl -s "https://api.github.com/users/eq19/events/public" | jq ".[0].payload.commits[0].message") >> ${GITHUB_ENV}

    - name: ⏪ Rewind all jobs on failure
      shell: bash
      run: |
        if [[ ${{ inputs.id }} == 3 && '${{ inputs.failure_status }}' == 'false' ]]; then
 
          cd ${{ github.workspace }} && mv -f docs ${RUNNER_TEMP}/
          ls -al /home/runner/_site && rm -rf /home/runner/_site/docs

          rm -rf * && mv -f /home/runner/_site/* . && mv -f ${RUNNER_TEMP}/docs .
          git add . && git commit --allow-empty -m ${{ env.LATEST_COMMIT }} && git push
 
        elif [[ '${{ inputs.failure_status }}' == 'true' ]]; then
      
          git clone --single-branch --branch 'gh-pages' ${{ env.REMOTE_REPO }} gh-pages && cd gh-pages
          #git add . && git commit --allow-empty -m "rerun due to job failure" && git push
  
        fi
