name: 'Jekyll Deploy Action'
description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages
inputs:
  provider:
    description: 'The deploy provider'
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false
  credentials:
    description: 'The gcloud credentials'
    required: true
  repository:
    description: 'The deploy repository'
    required: false
  branch:
    description: 'The deploy branch'
    required: false
  actor:
    description: 'The github username creating the commit'
    required: false
  gell_mann:
    description: 'The pre-build configuration'
    required: true

branding:
  icon: 'command'
  color: 'red'

runs:
  #using: 'node20'
  #main: '.github/run/main.js'
  #post: '.github/run/post.js'
  #post-if: 'success()'
  using: composite
  
  steps:

    - name: Authentication
      if: runner.os != 'macOS'
      uses: 'google-github-actions/auth@v2'
      id: 'auth'
      with:
        credentials_json: '${{ inputs.credentials }}'

    - name: ⏪ Rewind all jobs
      if: failure() || (runner.os == 'macOS' && contains(needs.*.result, 'failure'))
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}

        git config --global user.name "${GITHUB_ACTOR}"
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        REMOTE_REPO="https://${GITHUB_ACTOR}:${GITHUB_ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git remote set-url origin ${REMOTE_REPO} && git add . && git commit --allow-empty -m "rerun actions due to job failure" && git push
